"""initial schema

Revision ID: 479380a03489
Revises: 
Create Date: 2026-09-07 12:59:38.549498
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('welcome_screen', sa.Text(), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forms_slug'), ['slug'], unique=True)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('ix_questions_form_position', ['form_id', 'position'], unique=False)

    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index('ix_responses_form', ['form_id', 'submitted_at'], unique=False)

    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_title', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('number_value', sa.Float(), nullable=True),
    sa.Column('bool_value', sa.Boolean(), nullable=True),
    sa.Column('option_ids', sa.Text(), nullable=True),
    sa.Column('display_value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_answer_response_question')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index('ix_answers_question', ['question_id'], unique=False)

    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_options')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index('ix_answers_question')

    op.drop_table('answers')
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index('ix_responses_form')

    op.drop_table('responses')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_form_position')

    op.drop_table('questions')
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forms_slug'))

    op.drop_table('forms')
    # ### end Alembic commands ###
